### ISSUE TITLE
Can i add codechef or codeforces problems

### ISSUE THREAD

**Issue by Abhicoder03** [asAshutosh/Hacktoberfest-Accepted#67]
Could you please assign me this issue.

**Comment by InnocentDaksh63** [comment]
please assign me for this issue i have been added a all possible codechef and codeforces  problems

**Comment by fleurdelis07** [comment]
Can I work on this issue

**Comment by Karthick986** [comment]
I have solved some problems and can add few solutions, plz assign to me!

**Comment by asAshutosh** [comment]
yes all of you can
